export  { default as About} from "./About"
export  { default as Facts } from "./Facts"
export  { default as Feature} from "./Feature"
export  { default as Hero} from "./Hero"
export  { default as Newsletter} from "./Newsletter"
export  { default as Projects} from "./Projects"
export  { default as Service} from "./Service"
export  { default as Team} from "./Team"
export  { default as Testimonial} from "./Testimonial"
